### ISSUE TITLE
When dbow3 trains surf features, there is a Karton and no result. Is there a bug in dbow3? What can we do to improve it?

### ISSUE THREAD

**Issue by watertianyi** [mpkuse/DBow3_easytouse#1]

**Comment by mpkuse** [comment]
Is this question related to this repo? If so please elaborate. If this is a general question about bag-of-words, I am afraid I cannot answer it.

**Comment by watertianyi** [comment]
Does dbow3 support surf？

**Comment by mpkuse** [comment]
Theoretically it can. You need to train the vocabulary yourself. I use this pretrained vocabulary (https://github.com/rmsalinas/DBow3/raw/master/orbvoc.dbow3). It was trained by rmsalinas (i think) and uses brief features. 

I hope this is what you were looking for

**Comment by watertianyi** [comment]
I used his source code for surf training vocabulary stuck, some people said it was a bug, but the author did not answer this question positively.

**Comment by mpkuse** [comment]
Well actually DBOW is for binary valued features. SURF is a float values features. If you want to really go with SUF based vocabulary, you could use FAB-MAP.
